### PR TITLE
 Fix a bug about predictions saving

### PR DESCRIPTION
**Pull request by smy1999**
Shape of `pred` is `dim[:1]`, for example, `256*256`.
I think it should save prediction result with same dim as test image.

### CODE REVIEW

**Comment by dbaranchuk** [comment]
hey, "save_predictions" is supposed to get "preds" as NxCxHxW array, where C=1. In this case, pred[0] just squeezes the array and makes it HxW.

**Comment by smy1999** [comment]
Thanks for your reply.
I trained classifier myself on your cat_15 dataset and training settings are same as yours. When I finished training and evalutated the model, I got 20 `npy` prediction files. Every one of `npy` files has a shape of `(256)`. Visualization results are well-behaved.
I found that `preds` is a python list which size is `testing_number`, and its item has a shape of `(256, 256)`.
Maybe `preds` is NxHxW, not NxCxHxW?

**Comment by dbaranchuk** [comment]
Yep, looks like you are right. Let's keep your changes then and also move [L119](https://github.com/yandex-research/ddpm-segmentation/blob/7450bfe82c35b04d22ed3e51390334d985c61e32/src/pixel_classifier.py#L119) right before [L117](https://github.com/yandex-research/ddpm-segmentation/blob/7450bfe82c35b04d22ed3e51390334d985c61e32/src/pixel_classifier.py#L117), just in case.

**Comment by dbaranchuk** [comment]
Thank you!

**Pull request merged**
